twig:
  default_path: '%kernel.project_dir%/templates'
  form_themes:
  - bootstrap_4_layout.html.twig
  globals:
    categoryRepository: "@App\\Repository\\CategoryRepository"
    trickDir: "uploads/trick/"
    userDir: "uploads/user/"
    videoDir: "uploads/video/"

knp_paginator:
  template:
    pagination: '@KnpPaginator/Pagination/twitter_bootstrap_v4_pagination.html.twig'
