twig:
  default_path: '%kernel.project_dir%/templates'
  form_themes:
  - bootstrap_4_layout.html.twig
  globals:
    categoryRepository: "@App\\Repository\\CategoryRepository"
    trickDir: "uploads/trick/"
    userDir: "uploads/user/"
knp_paginator:
  template:
  #    pagination: '@KnpPaginator/Pagination/sliding.html.twig'     # sliding pagination controls template
#    pagination: '@App/templates/pagination/sliding.html.twig'